services:
  - type: web
    name: stockvue-proxy
    env: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 22.21.0
